version: '3.3'

services:
  crawler:
    build: .
    environment:
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
    volumes:
      - ./data/candles/crawler/:/app/data/